#!/bin/bash

/sbin/iptables -P OUTPUT DROP
/sbin/iptables -P INPUT DROP
/sbin/iptables -P FORWARD DROP
/sbin/ip6tables -P OUTPUT DROP 2>/dev/null
/sbin/ip6tables -P INPUT DROP 2>/dev/null
/sbin/ip6tables -P FORWARD DROP 2>/dev/null

echo "Firewall is up, everything has to go through the vpn"
